name: Node.js Package Publish To NPM

on:
  push:
    tags:
      - v1.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12 
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm test
      - run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_GitHub_Token}}
